export {default as OnboardingImageOne} from './illustration1.png';
export {default as ManProfile} from './man-profile.jpg';
export {default as Location} from './location.png';
export {default as Email} from './email2.png';
export {default as Profile} from './details-icon.png';
export {default as ErrorIcon} from './error-icon-2.png';
export {default as Streamer} from './streamer.png';
export {default as OnlineMarketing} from './online-market.png';
export {default as Earn} from './earn.png';