export const env ={
    API_BASE_URL: process.env.EXPO_PUBLIC_API_URL || '',
    API_KEY: process.env.EXPO_PUBLIC_API_KEY || '',
    CLOUDINARY_CLOUD_NAME: process.env.EXPO_PUBLIC_CLOUDINARY_CLOUD_NAME || '',
    CLOUDINARY_API_KEY: process.env.EXPO_PUBLIC_CLOUDINARY_API_KEY || '',
    CLOUDINARY_API_SECRET: process.env.EXPO_PUBLIC_CLOUDINARY_API_SECRET || '',
    SOCKET_URL: process.env.EXPO_PUBLIC_SOCKET_URL || '',
}